name: devilutionx
base: core18
adopt-info: devilutionx
summary: DevilutionX - Diablo build for modern operating systems
description: |
    DevilutionX is a reimplementation of Blizzard's Diablo 1,
    developed by careful and deep analysis of the original game files.
    
    This allows you to play Diablo 1 on a wide variety of operating systems,
    including GNU/Linux.

    Even though DevilutionX is an open source project, the Diablo 1 game files
    are not free and protected by Blizzard's copyright.
    
    Therefore, you need to provide your own legitimate copy of the game.
confinement: strict
grade: stable

apps:
  devilutionx:
    command: desktop-launch $SNAP/usr/bin/devilutionx
    plugs:
      - x11
      - wayland
      - unity7
      - audio-playback
      - joystick
      - network
      - network-bind

layout:
  /usr/share/fonts/truetype:
    bind: $SNAP/usr/share/fonts/truetype

parts:
  devilutionx:   
    plugin: cmake
    after: [desktop-glib-only]
    source: https://github.com/diasurgical/devilutionx.git
    source-type: git
    configflags:
      - '-DCMAKE_INSTALL_PREFIX=/usr'
      - '-DBINARY_RELEASE=ON'
    override-build: |
      snapcraftctl set-version "$(git -C $SNAPCRAFT_PART_SRC describe --tags)"
      snapcraftctl build

    build-packages:
      - cmake
      - g++
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libsodium-dev

    stage-packages:
      - libstdc++6
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglu1-mesa
      - libwayland-egl1-mesa
      - libsdl2-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libsodium23

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

