name: devilutionx
base: core20
adopt-info: devilutionx
summary: DevilutionX - Diablo build for modern operating systems
description: |
    DevilutionX is a reimplementation of Blizzard's Diablo 1,
    developed by careful and deep analysis of the original game files.
    
    This allows you to play Diablo 1 on a wide variety of operating systems,
    including GNU/Linux.

    Even though DevilutionX is an open source project, the Diablo 1 game files
    are not free and protected by Blizzard's copyright.
    
    Therefore, you need to provide your own legitimate copy of the game.
confinement: strict
grade: stable

apps:
  devilutionx:
    command: bin/desktop-launch $SNAP/usr/local/devilutionx/devilutionx --data-dir $SNAP_USER_COMMON
    plugs:
      - x11
      - wayland
      - unity7
      - opengl
      - audio-playback
      - joystick
      - network
      - network-bind

    environment:
      XDG_DATA_HOME: $SNAP_USER_COMMON/
      DBUS_FATAL_WARNINGS: 0

layout:
  /usr/share/fonts/truetype:
    bind: $SNAP/usr/share/fonts/truetype

parts:
  devilutionx:   
    plugin: nil
    after: [patches,desktop-glib-only]
    source: https://github.com/diasurgical/devilutionx.git
    source-type: git
    override-build: |
      last_committed_tag="$(git -C $SNAPCRAFT_PART_SRC describe --tags `git rev-list --tags --max-count=1`)"
      trimmed_tag="$(echo $last_committed_tag | sed 's/desc\///' | sed 's/git//' | sed 's/^v//')"
      last_released_tag="$(snap info devilutionx | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${trimmed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        snapcraftctl set-version $(git -C $SNAPCRAFT_PART_SRC describe --tags `git rev-list --tags --max-count=1` | sed 's/desc\///' | sed 's/git//' | sed 's/^v//')
      else
        snapcraftctl set-version "git"
      fi
      patch --binary -l ${SNAPCRAFT_PART_SRC}/Source/appfat.cpp -i ${SNAPCRAFT_STAGE}/patches/001-missing-diabdat-notice.patch
      mkdir build && cd build
      cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
      make -j$(nproc)
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/local/devilutionx/
      cp -a devilutionx 3rdParty assets ${SNAPCRAFT_PART_INSTALL}/usr/local/devilutionx/
      snapcraftctl build

    build-packages:
      - cmake
      - g++
      - libbz2-1.0
      - libbz2-dev
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libsodium-dev

    stage-packages:
      - libstdc++6
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglu1-mesa
      - libwayland-egl1-mesa
      - libsdl2-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libsodium23

  patches:
    source: snap/local/
    plugin: dump

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

